name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  test_matrix:
    strategy:
      matrix:
        include:
          - os: windows-latest
            artifact_name: ${{ github.event.repository.name }}-windows-x64.exe
            alternate_artifact: ${{ github.event.repository.name }}.exe
            suffix: ".exe"
            rust_features: ""
          - os: windows-latest
            artifact_name: ${{ github.event.repository.name }}-pcap-and-pktmon.exe
            suffix: ".exe"
            rust_features: "--features pcap"
          - os: ubuntu-22.04
            artifact_name: ${{ github.event.repository.name }}-linux-x64
            suffix: ""
            rust_features: "--features pcap,static-libpcap"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - name: Cache
        uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Setup libpcap (Linux)
        if: runner.os == 'Linux'
        uses: ./.github/actions/setup-libpcap
      - name: Install Npcap SDK (Windows)
        if: runner.os == 'Windows'
        run: |
          curl https://npcap.com/dist/npcap-sdk-1.15.zip -o sdk.zip
          unzip sdk.zip
      - run: rustup component add clippy
      - run: cargo check --release ${{ matrix.rust_features }}
      - run: cargo fmt --check
      - run: cargo test --release ${{ matrix.rust_features }}
        env:
          LIB: ${{ github.workspace }}/Lib/x64/
      - run: cargo clippy --release ${{ matrix.rust_features }} -- -Dwarnings
      - run: cargo build --release ${{ matrix.rust_features }}
        env:
          LIB: ${{ github.workspace }}/Lib/x64/
      - if: ${{matrix.artifact_name}}
        name: Upload release artifact
        uses: actions/upload-artifact@v6
        with:
          name: ${{ matrix.artifact_name }}
          path: target/release/irminsul${{ matrix.suffix }}
      - if: ${{matrix.alternate_artifact}}
        name: Upload release artifact
        uses: actions/upload-artifact@v6
        with:
          name: ${{ matrix.alternate_artifact }}
          path: target/release/irminsul${{ matrix.suffix }}
